# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bwiow1_18Xd-RKvnVHeVrnlx2wGmmCu
"""

import pandas as pd
import os

# Ensure data_clean directory exists
os.makedirs("data_clean", exist_ok=True)

# Load dataset
file_path = "/content/frailty_data.csv"
df = pd.read_csv(file_path)

# Standardize column names (lowercase and replace spaces with underscores)
df.columns = df.columns.str.lower().str.replace(" ", "_")

# Convert Frailty (Y/N) to numeric (1 for Yes, 0 for No)
df["frailty"] = df["frailty"].map({"Y": 1, "N": 0})

# Fill missing numerical values with the mean
for col in df.select_dtypes(include=["number"]).columns:
    df[col].fillna(df[col].mean(), inplace=True)

# Save cleaned dataset
cleaned_file_path = "data_clean/cleaned_frailty_data.csv"
df.to_csv(cleaned_file_path, index=False)

print("Data cleaning complete. Missing values replaced with mean. Cleaned data saved at:", cleaned_file_path)