# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwmYPZtjJsTGF9omiG5m93NXLAC9jqf9
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load cleaned dataset
cleaned_data_path = "/content/cleaned_frailty_data.csv"
df = pd.read_csv(cleaned_data_path)

# Standardize column names (convert to lowercase and strip spaces)
df.columns = df.columns.str.lower().str.strip()
print("Updated Column Names:", df.columns)

# Ensure results directory exists
os.makedirs("results", exist_ok=True)

# Compute and save summary statistics
summary_stats = df.describe()
summary_stats.to_csv("results/summary_statistics.txt")

# Compute and save correlation matrix
correlation_matrix = df.corr()
correlation_matrix.to_csv("results/correlation_matrix.csv")

print(" Data analysis completed. Results saved.")

#  Check if 'grip_strength' exists in the dataset
grip_col = None
for col in df.columns:
    if "grip" in col.lower():  # Look for variations like 'grip strength' or 'grip_strength'
        grip_col = col
        break

if grip_col is None:
    raise KeyError("Column related to 'Grip Strength' not found in dataset. Check column names.")

# **Visualization: Bar Chart - Average Grip Strength by Frailty Status**
plt.figure(figsize=(6, 4))
sns.barplot(x=df["frailty"], y=df[grip_col], estimator=lambda x: x.mean(), ci=None, palette="coolwarm")
plt.title("Average Grip Strength by Frailty Status")
plt.xlabel("Frailty (1 = Yes, 0 = No)")
plt.ylabel("Average Grip Strength (kg)")
plt.xticks(ticks=[0, 1], labels=["No Frailty", "Frail"])
plt.grid()

# Save visualization
plot_path = "results/average_grip_strength_frailty.png"
plt.savefig(plot_path)
plt.show()

print("Bar chart saved in 'results/' directory.")