# -*- coding: utf-8 -*-
"""student_dataanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UT9N35cTT51lfhYWgS0G-nVgD2CiT85w
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load cleaned dataset
cleaned_data_path = "/content/cleaned_students_performance.csv"
df = pd.read_csv(cleaned_data_path)

# Print column names to verify structure
print("Updated Column Names:", df.columns)

# Ensure results directory exists
os.makedirs("results", exist_ok=True)

# Convert categorical variables to numeric encoding
for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype("category").cat.codes  # Convert categorical values to numeric codes

# Compute and save summary statistics
summary_stats = df.describe()
summary_stats.to_csv("results/summary_statistics.txt")

# Compute and save correlation matrix (after converting categorical columns)
correlation_matrix = df.corr()
correlation_matrix.to_csv("results/correlation_matrix.csv")

print(" Data analysis completed. Results saved.")

# Histogram - Distribution of Math, Reading, and Writing Scores**
plt.figure(figsize=(12, 5))
subjects = ['math_score', 'reading_score', 'writing_score']
df[subjects].hist(bins=15, figsize=(15, 5), layout=(1, 3), edgecolor='black')
plt.suptitle('Distribution of Scores in Mathematics, Reading, and Writing')
plt.savefig("results/score_distribution.png")
plt.show()
print(" Histogram saved.")

# Gender-wise Average Scores Across Subjects**
df_melted = df.melt(id_vars='gender', value_vars=subjects, var_name='Subject', value_name='Score')
plt.figure(figsize=(10, 6))
sns.barplot(x='Subject', y='Score', hue='gender', data=df_melted, ci=None, palette='muted')
plt.title('Gender-wise Average Scores Across Subjects')
plt.ylabel('Average Score')
plt.savefig("results/gender_wise_scores.png")
plt.show()
print("Gender-wise Bar Chart saved.")

#  Box Plot - Impact of Parental Education Level on Math Scores**
plt.figure(figsize=(12, 6))
sns.boxplot(x='parental_level_of_education', y='math_score', data=df, palette='pastel')
plt.title('Impact of Parental Education Level on Math Scores')
plt.xticks(rotation=45)
plt.ylabel('Math Score')
plt.savefig("results/parental_education_vs_scores.png")
plt.show()
print("Box Plot saved.")

# Scatter Plot - Reading Scores vs Writing Scores**
plt.figure(figsize=(8, 6))
sns.scatterplot(x=df['reading_score'], y=df['writing_score'], alpha=0.6, edgecolor=None)
plt.title('Reading Scores vs Writing Scores')
plt.xlabel('Reading Score')
plt.ylabel('Writing Score')
plt.grid()
plt.savefig("results/reading_vs_writing_scores.png")
plt.show()
print("Scatter Plot saved.")

#  Heatmap - Correlation of Variables**
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='viridis', linewidths=0.5)
plt.title('Correlation Heatmap of Student Performance Variables')
plt.savefig("results/correlation_heatmap.png")
plt.show()
print("Heatmap saved.")